# Site settings
title: Musik Lovers
description: An analysis of Konzerthaus events
keywords: Classical Music, Coding Da Vinci
author: Adsidera, Carole
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
